name: Get changed cargo packages
description: ""

inputs:
  token:
    description: ""
    default: ${{ github.token }}

outputs:
  changed-cargo-packages:
    description: ""

runs:
  using: node20
  main: dist/main.js
