name: Get changed Cargo packages
description: "x"

branding:
  icon: info
  color: yellow

inputs:
  token:
    description: ""
    default: ${{ github.token }}
  path:
    description: ""
    default: .

outputs:
  changed-cargo-packages:
    description: ""

runs:
  using: node20
  main: dist/main.js
